---

- name: "block: backup existing bind9 files"
  block:
    - name: "bind9: backup dest: {{ bind9_backup_path }}"
      file:
        state: directory
        path: "{{ bind9_backup_path }}"
        recurse: yes
      tags:
        - role:bind9:backup
        - role:bind9:installation
        - role:bind9:configuration
        - role:bind9:logging
        - role:bind9:zones:change

    - name: "bind9: create temporary backup location on host"
      tempfile:
        state: directory
        path: "{{ bind9_backup_path }}"
        suffix: bind9-backup
      register: bind9_backup_path_latest
      tags:
        - role:bind9:backup
        - role:bind9:installation
        - role:bind9:configuration
        - role:bind9:logging
        - role:bind9:zones:change

    - name: "bind9: backup existing critical files"
      copy:
        remote_src: yes
        src: "{{ item }}"
        dest: "{{ bind9_backup_path_latest.path }}/{{ item | basename }}"
      loop:
        - "{{ bind9_path_default_bind }}"
        - "{{ bind9_path_logrotated_bind }}"
      register: bind9_backup_content_files
      tags:
        - role:bind9:backup
        - role:bind9:installation
        - role:bind9:configuration
        - role:bind9:logging
        - role:bind9:zones:change

    - name: "bind9: create archive backup of {{ bind9_path_etc }}"
      community.general.archive:
        path: "{{ bind9_path_etc }}/"
        dest: "{{ bind9_backup_path_latest.path }}/bind9.etc.bind.gz"
        format: gz
        force_archive: true
      register: bind9_backup_archive
      tags:
        - role:bind9:backup
        - role:bind9:installation
        - role:bind9:configuration
        - role:bind9:logging
        - role:bind9:zones:change