---

- name: create build directory for the generated zones
  ansible.builtin.file:
    name: _zones 
    state: directory
  tags:
    - gha:bind9:build:zones
    - never

- name: generate zonefiles for testing
  template:
    src: "{{ bind9_templates | default('') }}bind/zones/db.template.j2"
    dest: _zones/db.{{ item.name }}
    mode: 0644
  with_items: "{{ bind9_zones_dynamic }}"
  when:
    - bind9_authoritative|default()
    - item.type|default(bind9_zone_type) == 'master'
  tags:
    - gha:bind9:build:zones
    - never