

- name: "block: rndc"
  block:
    - name: install bind9 rndc key
      template:
        src: "{{ bind9_templates | default('') }}bind/rndc.key.j2"
        dest: /etc/bind/rndc.key
        owner: "{{ bind9_user }}"
        group: "{{ bind9_group }}"
        mode: 0640
      when: bind9_rndc_key|default()
      notify:
        - restart bind9
      tags:
        - role:bind9:rndc_key
        - role:bind9:installation
        - role:bind9:configuration
        - role:bind9:zones:change

  rescue:

    - name: "bind9: stop service '{{ bind9_service_name }}'"
      ansible.builtin.service:
        name: "{{ bind9_service_name }}"
        state: stopped
      tags:
        - role:bind9:restore

    - name: "bind9: restoring {{ bind9_path_etc }}"
      ansible.builtin.unarchive:
        remote_src: yes
        src: "{{ bind9_backup_path_latest.path }}/bind9.etc.bind.gz"
        dest: "{{ bind9_path_etc }}"
        owner: root
        group: "{{ bind9_group }}"
      tags:
        - role:bind9:restore

    - name: "bind9: restoring system files"
      ansible.builtin.copy:
        remote_src: yes
        src: "{{ bind9_backup_path_latest.path }}/{{ item | basename }}"
        dest: "{{ item }}"
        owner: root
        group: "{{ bind9_group }}"
        mode: 0644
      loop:
        - "{{ bind9_path_default_bind }}"
        - "{{ bind9_path_logrotated_bind }}"
      tags:
        - role:bind9:restore

    - name: "bind9: restart bind service - {{ bind9_servie_name }}"
      ansible.builtin.service:
        name: "{{ bind9_service_name }}"
        state: restarted
      tags:
        - role:bind9:restore
