---

bind9_version: 9.16.1
bind9_backup_path: "/home/{{ ansible_user }}/bind9/backups"

bind9_path_default_bind: /etc/default/bind9
bind9_path_logrotated_bind: /etc/logrotate.d/bind
bind9_path_etc: /etc/bind

bind9_named_conf_files:
  - "/etc/bind/named.conf.options"
  - "/etc/bind/named.conf.local"
  - "/etc/bind/named.conf.default-zones"

# User and group for bind
bind9_user: bind
bind9_group: bind

bind9_service_name: named

# Listen on IPv6 interfaces
bind9_ipv6: yes

# Run bind as a DNS recursor?
bind9_recursor: no

# Run bind as authoritative nameserver?
bind9_authoritative: no

# run bind with forwarding?
bind9_forward: no

# Setup DNSSEC for recursor and zones?
bind9_dnssec: no

# set QNAME minimization behavior in the BIND resolver; atm bind9 default is relaxed
bind9_qname_minimization: "relaxed"

# DNSSEC validation mode (yes/no/auto)
bind9_dnssec_validation: "auto"

# Run bind as a hidden master (i.e. limit queries to our_networks)
bind9_hidden_master: no

# Only notify nameservers from also-notify, not from the zone NS records.
# Necessary to keep traffic between nameservers in private network.
bind9_notify_explicit: no

# Default zone type
bind9_zone_type: master

# Permitted hosts/networks for recursion (when configured as recursor)
bind9_our_networks:
  - localhost
  - localnets

# Permitted hosts/networks for zone transfers
bind9_our_neighbors:
  - localhost
  - localnets

# Install custom rndc.key
bind9_rndc_algorithm: hmac-md5
# bind9_rndc_key:

# Global primaries for all zones (if configured as secondary)
# bind9_masters:
#  - name: ns-primary
#    addresses:
#      - 1.2.3.4

# Primaries for particular zones (if configured as secondary)
# bind9_masters_extra:
#  - name: ns-primary
#    addresses:
#      - 1.2.3.4

# Global secondaries for all zones (if configured as primary)
# bind9_slaves:
#  - 1.2.3.4

# Enable BIND's XML statistics-channels (for monitoring purposes)
bind9_statistics_enabled: False

bind9_zones_dynamic: []
bind9_zones_static: []

# Authoritative include files
bind9_authoritative_includes: []

# DNSSEC is activated for all DNS zones per default
bind9_dnssec_zones_default_enabled: true


bind9_packages:
  - "bind9={{ bind9_version }}"
  - dnsutils

# Directory for bind9 files templates
bind9_templates: ""
# The default value takes templates form the {{ role_path }}/templates/ directory of the role
# You can set your own templates, for example with:
# bind9_templates: "{{ playbook_dir }}/host_vars/<my_host>/templates/"

# Logging
bind9_named_logging: False
bind9_log_path: /var/log/bind
bind9_log_severity: warning  # critical | error | warning | notice | info | debug [ level ] | dynamic
bind9_log_versions: 3
bind9_log_size: 60m           # Time units

bind9_log_categories:
  - name: default
    destination: bind_log
  - name: update
    destination: bind_log
  - name: update-security
    destination: bind_log
  - name: security
    destination: default_syslog
  - name: queries
    destination: bind_log
  - name: lame-servers
    destination: 'null'
