---

- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: reload bind9
  service:
    name: bind9
    state: reloaded

- name: zone file change
  debug:
    msg: "dummy handler"
