---

bind9_user: bind
bind9_group: bind
bind9_ipv6: no
bind9_recursor: yes
bind9_authoritative: no

bind9_forward: yes
bind9_forward_servers:
  - 128.111.1.1
  - 128.111.1.2

bind9_dnssec: no
bind9_dnssec_validation: "no"
bind9_qname_minimization: "relaxed"
bind9_hidden_master: no
bind9_notify_explicit: yes
bind9_zone_type: slave

bind9_our_networks:
  - localhost
  - '128.111.87.0/24'
  - '128.111.95.0/24'
  - '128.111.96.0/24'
  - '128.111.97.0/24'
  - '10.0.0.0/8'

bind9_our_neighbors:
  - localhost
  - 128.111.87.27
  - 128.111.1.1
  - 128.111.1.2
  - 98.173.28.161

bind9_rndc_algorithm: hmac-md5
bind9_rndc_key: "IEygmPeCmuO6nsOCvS6ddw=="

# Primaries for particular zones (if configured as secondary)
# bind9_masters_extra:
#  - name: ns-primary
#    addresses:
#      - 1.2.3.4
bind9_statistics_enabled: False
bind9_zones_static:
  - name: library.ucsb.edu
    type: slave 
  - name: alexandria.ucsb.edu
    type: slave 
  - name: 87.111.128.in-addr.arpa
    type: slave 
  - name: 95.111.128.in-addr.arpa
    type: slave
  - name: 96.111.128.in-addr.arpa
    type: slave 
  - name: 97.111.128.in-addr.arpa
    type: slave
  - name: 3.10.in-addr.arpa
    type: slave 
  - name: 11.10.in-addr.arpa
    type: slave 
  - name: 12.10.in-addr.arpa
    type: slave 

bind9_authoritative_includes: []
bind9_dnssec_zones_default_enabled: false

bind9_packages:
  - bind9
  - dnsutils

# Directory for bind9 files templates
bind9_templates: "{{ playbook_dir }}/templates/"

# Logging
bind9_named_logging: true
bind9_log_path: /var/log/named
bind9_log_severity: info  # critical | error | warning | notice | info | debug [ level ] | dynamic
bind9_log_versions: 3
bind9_log_size: 60m           # Time units

bind9_log_categories:
  - name: default
    destination: bind_log
  - name: config
    destination: bind_log
  - name: update
    destination: bind_log
  - name: update-security
    destination: bind_log
  - name: security
    destination: bind_log
  - name: queries
    destination: bind_log
  - name: resolver
    destination: bind_log


## Stuff we don't use
# Send DNSSEC KSK in DNSKEY and DS format over XMPP after it got created
bind9_dnssec_notify_xmpp: no
bind9_dnssec_notify_xmpp_user: user@jabber.example.org
bind9_dnssec_notify_xmpp_password: insecure
bind9_dnssec_notify_xmpp_rcpt: admin@jabber.example.org
bind9_dnssec_notify_xmpp_host: "{{ ansible_jabber_host|default('localhost') }}"

# Send DNSSEC KSK in DNSKEY and DS format over matrix webhook after it got created
bind9_dnssec_notify_matrix: no
bind9_matrix_notifier_url: ""

bind9_matrix_notifier_format: plain
bind9_matrix_notifier_text: ""
bind9_matrix_notifier_display_name: Ansible
bind9_matrix_notifier_avatar_url: https://cdn.icon-icons.com/icons2/2389/PNG/512/ansible_logo_icon_145495.png

bind9_matrix_notifier_body:
  text: "{{ bind9_matrix_notifier_text }}"
  format: "{{ bind9_matrix_notifier_format }}"
  displayName: "{{ bind9_matrix_notifier_display_name }}"
  avatarUrl: "{{ bind9_matrix_notifier_avatar_url }}"


# Install monit file for bind9 named
bind9_monit_enabled: no

